services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://adminuser:adminuser123@db:5432/admindatabase?sslmode=disable
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend/my-vue-app
      args:
        - VITE_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminuser123
      POSTGRES_DB: admindatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: